npm run lint:app
npm run lint:api
npm run build:app
npm run build:api
npm run bump:major
npm run changelog:major
npm run build:app 
npm run build:api
npm run deploy:app
npm run deploy:api
npm run deploy:git