npm run lint:angular
npm run lint:ionic
npm run lint:core
npm run lint:rr
npm run build:angular
npm run build:ionic
npm run build:core
npm run build:rr
npm run bump:patch
npm run changelog:patch
npm run deploy:git
npm run deploy:npm
npm run deploy:test
npm run tada