npm run lint:angular
npm run lint:ionic
npm run lint:core
npm run lint:rr
npm run build:angular
npm run build:ionic
npm run build:core
npm run build:rr
npm run bump:major
npm run changelog:major
npm run deploy:git
npm run deploy:npm
npm run tada