name: core
'on':
  push:
    branches:
      - master
    paths:
      - 'packages/core/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run core tests
        run: cd ./packages/core && npm test
      - name: Upload core coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/core/coverage
          fail_ci_if_error: true
          name: core
          verbose: true
